//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personaldetails.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class details
    {
        public long Id { get; set; }
        [Required(ErrorMessage="This Field is Required")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string FatherName { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string MotherName { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Location { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public string Bloodgroup { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public System.DateTime Dob { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public int Age { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public long Phonenumber { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        public Nullable<bool> IsActive { get; set; }
    }
}
